# Generated by Django 6.0.6 on 2026-06-09 17:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name / Naam')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='Phone / Mobile')),
                ('alternate_phone', models.CharField(blank=True, max_length=15, verbose_name='Alternate Phone / Doosra Number')),
                ('address', models.TextField(blank=True, verbose_name='Address / Pata')),
                ('aadhar_number', models.CharField(blank=True, max_length=12, verbose_name='Aadhar Number / Aadhar Sankhya')),
                ('role', models.CharField(choices=[('farmer', 'Farmer / Kisan'), ('guard', 'Guard / Chowkidar'), ('driver', 'Driver / Chalak'), ('helper', 'Helper / Sahayak'), ('supervisor', 'Supervisor / Mukhiya'), ('other', 'Other / Anya')], default='farmer', max_length=20, verbose_name='Role / Pad')),
                ('daily_wage', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Daily Wage (₹) / Roz ki Mazdoori')),
                ('joining_date', models.DateField(verbose_name='Joining Date / Joining ki Tarikh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active? / Kaam pe hai?')),
                ('leaving_date', models.DateField(blank=True, null=True, verbose_name='Leaving Date / Chodne ki Tarikh')),
                ('advance_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Advance Balance (₹) / Kul Advance Bakaya')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Tiippani')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Added On / Jab Joda')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated / Aakhri Update')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_given', models.DateField(verbose_name='Date Advance Given / Advance Dene ki Tarikh')),
                ('amount_given', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Amount Given (₹) / Di Gayi Rakam')),
                ('amount_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount Deducted (₹) / Kati Gayi Rakam')),
                ('reason', models.TextField(blank=True, verbose_name='Reason / Karan')),
                ('is_fully_recovered', models.BooleanField(default=False, verbose_name='Fully Recovered? / Poora Wapas Hua?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='employees.employee', verbose_name='Employee / Karmachari')),
            ],
            options={
                'verbose_name': 'Advance Payment / Peshgi Bhugtaan',
                'verbose_name_plural': 'Advance Payments / Peshgi Bhugtaan Records',
                'ordering': ['-date_given'],
            },
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Payment Date / Payment ki Tarikh')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Amount (₹) / Rakam')),
                ('payment_type', models.CharField(choices=[('wages', 'Daily Wages / Roz ki Mazdoori'), ('advance', 'Advance / Peshgi'), ('bonus', 'Bonus / Inaam'), ('travel', 'Travel Allowance / Yatra Bhatta'), ('other', 'Other / Anya')], default='wages', max_length=10, verbose_name='Payment Type / Bhugtaan Prakar')),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash / Nakad'), ('upi', 'UPI / GPay / PhonePe'), ('bank', 'Bank Transfer / Bank'), ('other', 'Other / Anya')], default='cash', max_length=10, verbose_name='Payment Mode / Bhugtaan Tarika')),
                ('description', models.TextField(blank=True, verbose_name='Description / Vivaran')),
                ('is_advance_deducted', models.BooleanField(default=False, verbose_name='Advance Deducted? / Advance Kata?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to='employees.employee', verbose_name='Employee / Karmachari')),
            ],
            options={
                'verbose_name': 'Expenditure / Vyay',
                'verbose_name_plural': 'Expenditures / Vyay Records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date / Tarikh')),
                ('status', models.CharField(choices=[('full', 'Full Day / Pura Din'), ('half', 'Half Day / Aadha Din'), ('absent', 'Absent / Gaair Haazir'), ('holiday', 'Holiday / Chutti'), ('leave', 'Leave / Avkash')], default='full', max_length=10, verbose_name='Status / Haalat')),
                ('check_in_time', models.TimeField(blank=True, null=True, verbose_name='Check In Time / Aane ka Waqt')),
                ('check_out_time', models.TimeField(blank=True, null=True, verbose_name='Check Out Time / Jaane ka Waqt')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Tiippani')),
                ('marked_by', models.CharField(blank=True, max_length=100, verbose_name='Marked By / Kisne Lagaaya')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employee', verbose_name='Employee / Karmachari')),
            ],
            options={
                'verbose_name': 'Attendance / Haziri',
                'verbose_name_plural': 'Attendance Records / Haziri Records',
                'ordering': ['-date', 'employee__name'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SalarySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'January / January'), (2, 'February / February'), (3, 'March / March'), (4, 'April / April'), (5, 'May / May'), (6, 'June / June'), (7, 'July / July'), (8, 'August / August'), (9, 'September / September'), (10, 'October / October'), (11, 'November / November'), (12, 'December / December')], verbose_name='Month / Mahina')),
                ('year', models.IntegerField(verbose_name='Year / Saal')),
                ('total_days_in_month', models.IntegerField(default=0, verbose_name='Total Working Days / Kul Kaam ke Din')),
                ('full_days', models.IntegerField(default=0, verbose_name='Full Days Present / Pura Din Aya')),
                ('half_days', models.IntegerField(default=0, verbose_name='Half Days Present / Aadha Din Aya')),
                ('absent_days', models.IntegerField(default=0, verbose_name='Absent Days / Gaair Haazir Din')),
                ('daily_wage_at_time', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Daily Wage at that time (₹) / Us waqt ki Roz ki Mazdoori')),
                ('gross_wages', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Gross Wages (₹) / Kul Mazdoori')),
                ('advance_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Advance Deducted (₹) / Kati Gayi Peshgi')),
                ('bonus_added', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Bonus Added (₹) / Joda Gaya Inaam')),
                ('net_payable', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Net Payable (₹) / Net Dene Layak Rakam')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Salary Paid? / Salary Di Gayi?')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Date Paid / Di Gayi Tarikh')),
                ('payment_mode', models.CharField(blank=True, choices=[('cash', 'Cash / Nakad'), ('upi', 'UPI / GPay / PhonePe'), ('bank', 'Bank Transfer / Bank'), ('other', 'Other / Anya')], default='cash', max_length=10, verbose_name='Payment Mode / Bhugtaan Tarika')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Tiippani')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_slips', to='employees.employee', verbose_name='Employee / Karmachari')),
            ],
            options={
                'verbose_name': 'Salary Slip / Vetan Parchi',
                'verbose_name_plural': 'Salary Slips / Vetan Parchian',
                'ordering': ['-year', '-month', 'employee__name'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
