# Generated by Django 6.0.6 on 2026-06-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('permanent', 'स्थायी'), ('daily', 'दिहाड़ी'), ('trainee', 'प्रशिक्षु'), ('skilled', 'कुशल मजदूर')], default='daily', max_length=20, verbose_name='Employee Type / कर्मचारी प्रकार'),
        ),
    ]
