# Generated by Django 6.0.6 on 2026-06-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='actual_wage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='employee',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=2, verbose_name='Alternate Phone / Doosra Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
